name: MyRickAndMorty
options:
  bundleIdPrefix: com.myrickandmorty
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "13.2.1"
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 7.1.2
  CombineMoya:
    url: https://github.com/Moya/Moya
    version: 15.0.0
  SwiftUI_CSS:
    url: https://github.com/hite/SwiftUI-CSS
    branch: master
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    version: 0.9.5
targets:
  MyRickAndMortyApp:
    type: application
    platform: iOS
    sources: [MyRickAndMorty]
    dependencies:
      - package: Kingfisher
      - package: CombineMoya
      - package: SwiftUI_CSS
    info:
      path: MyRickAndMorty/Info.plist
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.5"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
  MyRickAndMortyTests:
    type: bundle.unit-test
    platform: iOS
    sources: [MyRickAndMortyTests]
    dependencies:
      - target: MyRickAndMortyApp
      - package: ViewInspector
    info:
      path: MyRickAndMortyTests/Info.plist
