name: MyRickAndMorty
options:
  bundleIdPrefix: com.myrickandmorty
  deploymentTarget:
    iOS: 14.0
  xcodeVersion: "13.2.1"
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 7.1.2
  CombineMoya:
    url: https://github.com/Moya/Moya
    version: 15.0.0
targets:
  MyRickAndMortyApp:
    type: application
    platform: iOS
    sources: [MyRickAndMorty]
    dependencies:
      - package: Kingfisher
      - package: CombineMoya
    info:
      path: MyRickAndMorty/Info.plist
    preBuildScripts:
      - script: "mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "mint run swiftformat . --swiftversion 5.5"
        name: SwiftFormat
      - script: "mint run swiftlint"
        name: SwiftLint
